# Generated by Django 3.0.6 on 2020-05-26 06:24

from django.db import migrations, models
import register.uploads


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cucumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('identifier', models.CharField(max_length=75)),
                ('source_image', models.FileField(upload_to=register.uploads.image_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('identifier', models.CharField(max_length=25)),
            ],
        ),
    ]
