# Generated by Django 3.0.6 on 2020-05-29 01:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import register.uploads


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('identifier', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Cucumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=75)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('source_image', models.FileField(upload_to=register.filename.image_upload_path)),
                ('features', django.contrib.postgres.fields.jsonb.JSONField()),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Tank')),
            ],
        ),
    ]
