# Generated by Django 3.0.6 on 2020-05-29 04:10

from django.db import migrations, models
import register.filename


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cucumber',
            name='source_image',
            field=models.ImageField(upload_to=register.filename.image_upload_path),
        ),
    ]
