# Generated by Django 3.0.6 on 2020-06-28 07:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cucumber',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
