# Generated by Django 3.0.6 on 2020-06-28 07:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_cucumber_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cucumber',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
