# Generated by Django 3.0.6 on 2020-05-29 04:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200529_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cucumber',
            name='features',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
