# Generated by Django 3.0.6 on 2020-06-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20200529_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cucumber',
            name='identifier',
            field=models.CharField(max_length=75, unique=True),
        ),
        migrations.AlterField(
            model_name='tank',
            name='identifier',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
