# Generated by Django 3.0.6 on 2020-06-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20200602_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cucumber',
            name='identifier',
            field=models.CharField(max_length=75),
        ),
    ]
