# Generated by Django 3.0.6 on 2020-07-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_matchrecord_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
