# Generated by Django 3.0.6 on 2020-06-14 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_auto_20200614_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchrecord',
            name='failed',
        ),
        migrations.RemoveField(
            model_name='matchrecord',
            name='matches',
        ),
    ]
