# Generated by Django 3.0.6 on 2020-06-16 06:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_auto_20200614_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='backup_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='rejected_matches',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
